### ISSUE TITLE
Flask problem

### ISSUE THREAD

**Issue by wissamsofiane1708** [larsKiefer/ontologysim#4]
I'm very interessed by your project. 
When I try to run flask, I have this error message: 
Traceback (most recent call last):
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\Flask\FlaskMain.py", line 38, in <module>
    main()
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\Flask\FlaskMain.py", line 32, in main
    a = FlaskAppWrapper('wrap', init, {'production': production_config_path, 'owl': owl_config_path,
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\Flask\FlaskApp.py", line 60, in __init__
    self.db = DataBase(self.app.config["SQLALCHEMY_DATABASE_URI"])
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\ProductionSimulation\database\DataBase.py", line 55, in __init__
    dataBaseURL = PathTest.check_file_path(dataBaseURL)
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\ProductionSimulation\utilities\path_utilities.py", line 51, in check_file_path
    return cls.check_file_path_current_dir_given(path,current_dir)
  File "C:\Users\wsofiane\Desktop\test mesure onto\simulation\ontologysim\ontologysim\ProductionSimulation\utilities\path_utilities.py", line 35, in check_file_path_current_dir_given
    raise Exception("path not found", path)
Exception: ('path not found', '/ontologysim/ProductionSimulation/database/SimulationRun.db')

How can I fix this problem?
Thanks for your response

**Comment by omnicortex** [comment]
You need to run `CreateDatabase.py` in `ontologysim/ProductionSimulation/database`. See [here](https://ontologysim.readthedocs.io/en/latest/tutorial/installation.html)
